version: '3.5'

services:
  material-sence:
    container_name: material-sense
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=development
